# File: azure-pipelines.yml

jobs:
- template: template-pipelines.yml  # Template reference
  parameters:
    name: sl6
    vmImage: 'ubuntu-16.04'
    dockername: 'gitlab-registry.cern.ch/lhcb-core/lbdocker/slc6-build:latest'
    LCG: 'LCG_93'
    artifact: 'test_sl6'
- template: template-pipelines.yml  # Template reference
  parameters:
    name: centos7
    vmImage:  'ubuntu-16.04'
    dockername: 'gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest'
    LCG: 'LCG_93'
    artifact: 'test_cs7'
